### ISSUE TITLE
malware.js file missing

### ISSUE THREAD

**Issue by Ba777** [hakanonymos/botnet-browser-chrome#3]
In the repository https://github.com/hakanonymos/execute-javascript-from-web-server, you have mentioned that the  malware.js code residing in the server path. But, It's missing in this current repository. Please help.

**Comment by hakanonymos** [comment]
in this context, the attacker tries to execute javascript from his web server, I'm talking about chrome or mozilla firefox extensions here ;
now this fonction execute javascript code works very well but it is a smal code

soon i will put a new function and a small video how it works
my chanel youtube :

https://www.youtube.com/watch?v=WcnqtnJ6Eio&t=161s

**Comment by hakanonymos** [comment]
malware.js is the file name of your javascript malware, it can be code to steal cookies or a keylogger .... etc
